name: Standard Test
on: [push, pull_request]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --ignore-scripts

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Test Docs Generation
        run: yarn docgen